// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchDynamicFrequency(arg1) {
  return window['go']['main']['App']['FetchDynamicFrequency'](arg1);
}

export function FetchTemperature() {
  return window['go']['main']['App']['FetchTemperature']();
}

export function GetCPU() {
  return window['go']['main']['App']['GetCPU']();
}

export function GetDiskUsage() {
  return window['go']['main']['App']['GetDiskUsage']();
}

export function GetHostInfo() {
  return window['go']['main']['App']['GetHostInfo']();
}

export function GetRAM() {
  return window['go']['main']['App']['GetRAM']();
}
