// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCPU():Promise<void>;

export function GetRAM():Promise<Record<string, number>>;
