// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {disk} from '../models';

export function FetchDynamicFrequency(arg1:number):Promise<Array<number>>;

export function FetchTemperature():Promise<Record<string, string>>;

export function GetCPU():Promise<main.CpuInformation>;

export function GetDiskUsage():Promise<Record<string, disk.UsageStat>>;

export function GetRAM():Promise<Record<string, number>>;
